function mygui()
f1= figure(1)
set(f1,'Name', 'Inpunt Window', 'NumberTitle', 'off','position', [573 438 750 420])
%title (' Input Window Lagerhalle ')

a= []
%Eingabe Länge [left bottom width height]

txtLaenge = uicontrol('Style','text',...
        'Position',[10 367 120 20],...
        'String','Länge [m]'); 
EditLaenge = uicontrol('style','edit',...
            'units','pixels',...
             'position',[105 367 100 25])       
%Eingabe Breite
        
txtBreit = uicontrol('Style','text',...
        'Position',[10 337 120 20],...
        'String','Breite [m]'); 
InfoBreit = uicontrol('Style','text',...
        'Position',[220 337 420 40],...
        'String','Ab einer Spannweite über 13m bzw. 26m wird die Geasmmtspannweite mittels Stützen gewährleistet. Maximalespannweite zwischen den Stüzten beträgt 13m, maximale Gesammtspannweite beträgt 39m');
EditBreite = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 337 100 25])
%Eingabe Höhe

txtHoehe = uicontrol('Style','text',...
        'Position',[10 307 120 20],...
        'String','Höhe [m]'); 
EditHoehe = uicontrol('style','edit','position',[105 307 100 25],...
        'String', num2str(a))  
            

            %Eingabe Binderabstand
txtBabst = uicontrol('Style','text',...
        'Position',[0 277 120 20],...
        'String','Binderabstand [m]'); 
EditBabst = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 277 100 25])
%Eingabe Bauteildimension
txtBabst = uicontrol('Style','text',...
        'Position',[0 245 120 20],...
        'String','Profiel Träger'); 
DdownBauDimT= uicontrol('Style', 'popup',...
             'String', {'IPE200','IPE220','IPE240','IPE260'},...
             'Position', [105 247 100 20],'background','w');
         
txtBabst = uicontrol('Style','text',...
        'Position',[0 220 120 20],...
        'String','Profiel Stütze'); 
DdownBauDimS= uicontrol('Style', 'popup',...
             'String', {'HEA200','HEA220','HEA240','HEA260'},...
             'Position', [105 220 100 20],'background','w');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         
%StarButton

PushbuttonStart = uicontrol('style','pushbutton',...
            'units','pixels',...
            'position',[430 20 100 25],...
            'string','Start',...
            'foregroundcolor','b',...
            'callback',{@Startbutton,}); 
        
        function Startbutton(hObject, eventdata) 
          b1=(str2num(get(EditLaenge, 'String')))
          b2=(str2num(get(EditBreite, 'string')))
          a=b1+b2
        set(EditHoehe, 'String', num2str(a));
     
        hallo= (get(DdownBauDimS, 'Value'))
        if   hallo == 'HEA200'
          display ('IS: bla, Dim: 0.2')
      end
      
        end
    
        end
        
        

        
        
        
