function mygui()
f= figure(1)
set(f,'NumberTitle', 'off', 'Name', sprintf('Date: %s', datestr(now, 0)))
%title (' Input Window Lagerhalle ')

a=1
%Eingabe Länge [left bottom width height]

txtLaenge = uicontrol('Style','text',...
        'Position',[10 367 120 20],...
        'String','Länge [m]'); 
EditLaenge = uicontrol('style','edit',...
            'units','pixels',...
            'String', '',...
            'position',[105 367 100 25])       
%Eingabe Breite
        
txtBreit = uicontrol('Style','text',...
        'Position',[10 337 120 20],...
        'String','Breite [m]'); 
EditBreite = uicontrol('style','edit',...
            'units','pixels',...
            'Strin','',...
            'position',[105 337 100 25])
%Eingabe Höhe

txtHoehe = uicontrol('Style','text',...
        'Position',[10 307 120 20],...
        'String','Höhe [m]'); 
EditHoehe = uicontrol('style','edit','position',[105 307 100 25],...
        'String', num2str(a))                    
        
%{
            %Eingabe Binderabstand
txtBabst = uicontrol('Style','text',...
        'Position',[0 277 120 20],...
        'String','Binderabstand [m]'); 
EditBabst = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 277 100 25])
%Eingabe Bauteildimension
txtBabst = uicontrol('Style','text',...
        'Position',[0 245 120 20],...
        'String','Binderabstand [m]'); 
DdownBauDim= uicontrol('Style', 'popup',...
             'String', {'IPE200','IPE220','IPE240','IPE260'},...
             'Position', [105 247 100 20],'background','w');
%}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         
%StarButton
PushbuttonStart = uicontrol('style','pushbutton',...
            'units','pixels',...
            'position',[430 20 100 25],...
            'string','Start',...
            'foregroundcolor','b',...
            'callback',{@Startbutton,}); 
        
        function Startbutton(hObject, eventdata) 
          a= (num2str(get(EditLaenge, 'userdata'))) + (num2str(get(EditBreite, 'userdata')))
        set(EditHoehe, 'String', num2str(a));
        end
        
        
        end
        
        

        
        
        
