f= figure(1)
set(f,'NumberTitle', 'off', 'Name', sprintf('Date: %s', datestr(now, 0)))
%title (' Input Window Lagerhalle ')


%Eingabe Länge [left bottom width height]

txtLaenge = uicontrol('Style','text',...
        'Position',[10 367 120 20],...
        'String','Länge [m]'); 
EditLaenge = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 367 100 25],...
            'string','',...
            'foregroundcolor','b',...
            'callback',{@Temp_call});
%Eingabe Breite
txtBreit = uicontrol('Style','text',...
        'Position',[10 337 120 20],...
        'String','Breite [m]'); 
EditBreite = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 337 100 25],...
            'string','',...
            'foregroundcolor','b',...
            'callback',{@Temp_call});
%Eingabe Höhe
txtHoehe = uicontrol('Style','text',...
        'Position',[10 307 120 20],...
        'String','Höhe [m]'); 
EditHoehe = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 307 100 25],...
            'string','',...
            'foregroundcolor','b',...
            'callback',{@Temp_call});
%Eingabe Binderabstand
txtBabst = uicontrol('Style','text',...
        'Position',[0 277 120 20],...
        'String','Binderabstand [m]'); 
EditBabst = uicontrol('style','edit',...
            'units','pixels',...
            'position',[105 277 100 25],...
            'string','',...
            'foregroundcolor','b',...
            'callback',{@Temp_call});
%Eingabe Bauteildimension
txtBabst = uicontrol('Style','text',...
        'Position',[0 245 120 20],...
        'String','Binderabstand [m]'); 
DdownBauDim= uicontrol('Style', 'popup',...
             'String', {'IPE200','IPE220','IPE240','IPE260'},...
             'Position', [105 247 100 20],'background','w');
        
        
